/**
* @author Suneel and Rakshitha
* @date 11/01/2023
* @description  This class is used constants of utilizedLeaveBalance Class
*
* CHANGE HISTORY
* ====================================================================================================
* DATE          NAME                    DESCRIPTION
* N/A           N/A                     N/A
* ====================================================================================================
**/
public class CP_leaveHistoryConstants {
	public static final String APPROVER_1_PENDING = 'Approver 1 Pending';
    public static final String PENDING = 'Pending';
    public static final String APPROVED = 'Approved';
    public static final String APPROVER_2_PENDING = 'Approver 2 Pending';
    public static final String ANNUAL_LEAVE = 'Annual Leave';
    public static final String COMPENSATORY_OFF = 'Compensatory Off ';
}