public class EMS_TM_GlobalConstants {
    //Constants
    public static final List<String> USERPROFILES = new List<String>{'System Administrator','TM Customer Community'};
    public static final String GLOBALPROJECTS = 'Global Projects';
    public static final String SYSTEMADMINISTRATOR = 'System Administrator';
    public static final String STATUS_LOCKED = 'Locked';
    public static final String STATUS_SAVED = 'Saved';
    public static final String STATUS_SUBMITTED = 'Submitted';
}