@IsTest
public class EMS_TM_GenericController_Test {
    @IsTest
    public static void ems_TM_GenericController_Test() {
          /*  String searchTerm = 's';
            String searchTermEmpty = '';
            String myObject = 'EMS_TM_Project__c';
            String filterEmpty = '';
            String filter = 'EMS_TM_StartDate__c < today';
        	EMS_TM_GenericController.search(searchTerm,myObject,filter);
        	EMS_TM_GenericController.search(searchTermEmpty,myObject,filterEmpty);
        	EMS_TM_GenericController.search(searchTerm,myObject,filterEmpty);
        	EMS_TM_GenericController.search(searchTermEmpty,myObject,filter);*/
    }
}