public class LeaveRequestConstant {
     public static final Id LOGGEDIN_USERID = UserInfo.getUserId();
     public static final String APPROVER_2_WAITING = 'Approver 1 Pending';
     public static final String APPROVER_3_WAITING = 'Approver 2 Pending';
     public static final String APPROVER_4_WAITING = 'Approver 3 Pending';
     public static final String APPROVED = 'Approved';
     public static final String PENDING = 'Pending';
     public static final String CANCELLED = 'Cancelled';
     public static final String REJECTED = 'Rejected';
     public static final String WORK_FROM_HOME= 'Work from Home';
     public static final String AUTO_APPROVED = 'Auto Approved';
     public static final String LOSS_OF_PAY ='Loss of Pay';
     public static final String ANNUAL_LEAVE ='Annual Leave';
    public static final String COMPENSATORY_OFF ='Compensatory Off';
    public static final String MATERNITY_LEAVE ='Maternity Leave';
 //   public static final String MATERNITY_LEAVE ='Maternity Leave';
}