public class LeaveRequestConstant {
     public static final Id LOGGEDIN_USERID = UserInfo.getUserId();
     public static final String APPROVER_2_WAITING = 'Waiting For Approver 2';
     public static final String APPROVER_3_WAITING = 'Waiting For Approver 3';
     public static final String APPROVED = 'Approved';
     public static final String PENDING = 'Pending';
     public static final String CANCELLED = 'Cancelled';
     public static final String REJECTED = 'Rejected';
     public static final String WORK_FROM_HOME= 'Work from Home';
}