#Full Validation Job

name: Full Validation Job 
run-name: Full Validation for  ${{github.ref_name}} to ${{ github.event.inputs.choice }}

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      choice:
        type: choice
        description: Select Org
        options:
        - EMS-Dev
        - EMS-Qa
     
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Full-Validation:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Running the Test Report
#        run: sfdx force:apex:test:run --testlevel RunLocalTests -u ${{ github.event.inputs.choice }} --resultformat json > /tmp/ndeploy.log
        run: sh /home/ec2-user/report.sh ${{ github.event.inputs.choice }}

  Generating-Report:
    runs-on: self-hosted
    needs : [Full-Validation]
    steps:
      - name: Generating Report
        run : echo "http://ec2-184-73-72-245.compute-1.amazonaws.com/report-${{ github.event.inputs.choice }}.html"
        
        
