# This is a basic workflow to help you get started with Actions

name: Validate to EMS-Dev Org

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
 # push:
 #   branches: [ "master" ]
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Validate:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
        
      - name: Validate Code to EMS Dev Org
        #run: sfdx force:source:deploy -c -p . -u EMS-Dev --testlevel=RunLocalTests
        run: sfdx force:apex:test:run --testlevel RunLocalTests -u EMS-Dev --resultformat json > /tmp/deploy.log
      - name: Reading the Deploy log
        run: cat /tmp/deploy.log| jq --raw-output '.result.tests|.[].Outcome="fail"|.[]|select(.Message !=null).FullName+"\nError Message = "+.Message+"\n================================================================================="'
      - name: Cleaning Deploy Log
        run: rm -rf /tmp/deploy.log
